# Generated by Django 2.2.11 on 2020-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_id',
            field=models.IntegerField(default=-1),
        ),
    ]
